pkg: de-lint ibmcloud package
Fixed errors caught by golangci-lint:

pkg/adaptor/hypervisor/ibmcloud/service.go:38:2: `subnetBits`
is unused (deadcode)
	subnetBits    = "/24"
	^
pkg/adaptor/hypervisor/ibmcloud/server.go:83:24: Error return value
of `s.ttRpc.Shutdown` is not checked (errcheck)
	defer s.ttRpc.Shutdown(context.Background())
	                      ^
pkg/adaptor/hypervisor/ibmcloud/server.go:89:13: Error return value
of `s.Shutdown` is not checked (errcheck)
		s.Shutdown()
		          ^
pkg/adaptor/hypervisor/ibmcloud/server_test.go:148:23: Error return
value of `ttrpcServer.Serve` is not checked (errcheck)
		if ttrpcServer.Serve(ctx, handler); err != nil {
		                    ^
pkg/adaptor/hypervisor/ibmcloud/shim_test.go:212:23: Error return value
of `ttrpcServer.Serve` is not checked (errcheck)
		if ttrpcServer.Serve(ctx, listener); err != nil {
		                    ^

Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>