pkg: de-lint forwarder package
Fixed errors caught by golangci-lint:

pkg/adaptor/forwarder/forwarder.go:92:13: Error return value of
`f.Shutdown` is not checked (errcheck)
		f.Shutdown()
		          ^
pkg/forwarder/daemon.go:122:13: Error return value of `d.Shutdown`
is not checked (errcheck)
		d.Shutdown()
		          ^
pkg/forwarder/daemon_test.go:56:21: func `(*mockBackend).Start`
is unused (unused)
func (*mockBackend) Start(ctx context.Context) error {
                    ^
pkg/forwarder/daemon_test.go:60:21: func `(*mockBackend).Shutdown`
is unused (unused)
func (*mockBackend) Shutdown() error {
                    ^
pkg/forwarder/daemon_test.go:54:6: type `mockBackend` is unused (unused)
type mockBackend struct{}
     ^
pkg/forwarder/daemon_test.go:63:21: func `(*mockBackend).AddHandler` is
unused (unused)
func (*mockBackend) AddHandler(pattern string, handler http.Handler)
error {
                    ^
pkg/forwarder/agent/forwarder_test.go:61:21: func
`(*mockBackend).Start`
is unused (unused)
func (*mockBackend) Start(ctx context.Context) error {
                    ^
pkg/forwarder/agent/forwarder_test.go:59:6: type `mockBackend` is
unused (unused)
type mockBackend struct{}
     ^
pkg/forwarder/agent/forwarder_test.go:68:21:
func `(*mockBackend).AddHandler`
is unused (unused)
func (*mockBackend) AddHandler(pattern string,
handler http.Handler) error {
                    ^
pkg/forwarder/agent/forwarder_test.go:65:21:
func `(*mockBackend).Shutdown`
is unused (unused)
func (*mockBackend) Shutdown() error {
                    ^
pkg/forwarder/daemon_test.go:95:2: S1000: should use a simple channel
send/receive instead of `select` with a single case (gosimple)
	select {
	^
pkg/forwarder/agent/forwarder_test.go:166:2: S1000: should use a simple
channel send/receive instead of `select` with a single case (gosimple)
	select {
	^
Fixes #32
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>