workflows: Install yq if not installed on self-hosted runners
Continuing on #2698, the following error was observed:

```
Run echo "MKOSI_VERSION=$(yq -e '.tools.mkosi' versions.yaml)" >> "$GITHUB_ENV"

  Error: open versions.yaml: no such file or directory
  Error: open versions.yaml: no such file or directory
```

after switching to IBM Actions Z runners.
The package is pre-installed at /usr/bin/yq for the runners.
Install the package only if it is not installed on the runners.

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>