libvirt: update GetDomainCapabilities to use ConnectGetDomainCapabilitiesFlags
Update the GetDomainCapabilities function signature to use
libvirt.ConnectGetDomainCapabilitiesFlags instead of uint32 to match
the updated libvirt API (v1.11010.0).

This fixes the compilation error:
libvirt/libvirt.go:134:83: cannot use flags (variable of type uint32)
as "libvirt.org/go/libvirt".ConnectGetDomainCapabilitiesFlags value

Assisted-by: Cursor
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>