helm: handle error if release is not found
Currently if the peerpods release does not exist or is already deleted,
running `make delete` throws an error as expected.
```
helm uninstall peerpods -n confidential-containers-system
Error: uninstall: Release not loaded: peerpods: release: not found
make: *** [Makefile:156: delete] Error 1
```
Handle this case for better readability.

Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>