workflow: retry caa image build
The CAA image build on push is very important to not fail otherwise
features and fixes don't properly get into devel/release cycle. But
we recently have noticed errors like:

ERROR: failed to solve: DeadlineExceeded: failed to push
quay.io/confidential-containers/cloud-api-adaptor:b277c1ae739ae31892
6ef4f39c88fac16050d13a: no active session for pj7teq3k1b3tqjew1y3tf5mgp:
context deadline exceeded

Error that goes away when the workflow is manually re-trigger after a few
minutes. So this added a retry mechanism that will try again the build
command after two minutes and for the maximum of three tentatives.

Fixes #1339
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>