pkg: de-lint util/http/upgrader package
Fixed errors caught by golangci-lint:

client.go:52:6: `emptyLogger` is unused (deadcode)
type emptyLogger log.Logger
     ^
server_test.go:85:20: Error return value of `writer.WriteString` is not checked (errcheck)
	writer.WriteString("non-empty buffer")
	                  ^
client.go:93:6: shadow: declaration of "err" shadows declaration at line 72 (govet)
		if err := tlsConn.Handshake(); err != nil {
		   ^
client.go:109:5: shadow: declaration of "err" shadows declaration at line 72 (govet)
	if err := req.Write(conn); err != nil {
	   ^
upgrader_test.go:39:6: shadow: declaration of "err" shadows declaration at line 29 (govet)
		if err := httpServer.Serve(listener); err != nil && !errors.Is(err, http.ErrServerClosed) {
		   ^
upgrader_test.go:54:8: shadow: declaration of "err" shadows declaration at line 29 (govet)
	if _, err := serverConn.Write([]byte(message)); err != nil {
	      ^
upgrader_test.go:57:5: shadow: declaration of "err" shadows declaration at line 29 (govet)
	if err := serverConn.Close(); err != nil {
	   ^

Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>