test/e2e: fix panic in getCaaPodLogForPod()
getCaaPodLogForPod() assumes that some caa logs exists after the pod is
launched, which is not always true. For example, on error below the pod
was launched, failed at runtime (before caa gets called), tried to
print the logs but panic'ed:

```
--- FAIL: TestAwsCreateSimplePod (1203.78s)
    --- FAIL: TestAwsCreateSimplePod/SimplePeerPod_test (1203.78s)
        --- FAIL: TestAwsCreateSimplePod/SimplePeerPod_test/PodVM_is_created (1.22s)
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 379 [running]:
testing.tRunner.func1.2({0x569dbe0, 0xc000f5f560})
        /usr/lib/golang/src/testing/testing.go:1734 +0x21c
testing.tRunner.func1()
        /usr/lib/golang/src/testing/testing.go:1737 +0x35e
panic({0x569dbe0?, 0xc000f5f560?})
        /usr/lib/golang/src/runtime/panic.go:792 +0x132
github.com/confidential-containers/cloud-api-adaptor/src/cloud-api-adaptor/test/e2e.getCaaPodLogForPod...
```

Assisted-by: Cursor
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>